### ISSUE TITLE
Does something funky with TXT records that contain domainkeys

### ISSUE THREAD

**Issue by Havoc302** [carlpett/tfz53#10]
Seems it put part of it into a comment above the record instead, very strange. Only a minor bug though, otherwise a real time saver, this tool is awesome.
![image](https://user-images.githubusercontent.com/8010786/54336862-62926e80-4681-11e9-98be-d8163aa617ec.png)

**Comment by carlpett** [comment]
Hey @Havoc302!
Did some quick testing, it looks like this happens if the value contains spaces and is not quoted. Could this be the case for you?

**Comment by carlpett** [comment]
Checked the [spec](https://tools.ietf.org/html/rfc1035), it indeed seems the quoting is required:
>**TXT-DATA**        One or more \<character-string>s.
>[...]
> \<character-string> is expressed in one or two ways: as a contiguous set
of characters without interior spaces, or as a string beginning with a "
and ending with a ".  Inside a " delimited string any character can
occur, except for a " itself, which must be quoted using \ (back slash).

It is fairly common that servers are a bit more... well, flexible, in their parsing than required by the spec. The parser used here is pretty strict though, so there's been a few cases like this where zones that work elsewhere are not accepted. (And in at least one case, where the zone had been broken for a number of years but noone had noticed)

**Comment by Havoc302** [comment]
You're actually spot on, thanks for checking that, all the other zones I've used the tool on it's been enclosed in quotes. Lucky this one wasn't prod :D
