### ISSUE TITLE
Windows version appends character to start of each file

### ISSUE THREAD

**Issue by Havoc302** [carlpett/tfz53#11]
After building a powershell script to use your tool and convert all the files over from BIND to TerraForm we discovered a weird bug where it was appending some special character to the start of the file, making Terraform fail to validate.

brendand@~/Documents/repos/ecosystem/terraform/aws-dns (prod)(master) $ head prod/allcloudcontent.com.au.resources.tf
��
resource

<img width="634" alt="Screen Shot 2019-03-18 at 1 44 27 pm" src="https://user-images.githubusercontent.com/8010786/54504428-b8b82800-4987-11e9-8f68-7bec511b4c85.png">

As you can see that was at the start of every file.

This character wasn't visible in Notepad, Notepad++, VSCode, Sublime, Vi or anything else I tried.

We ended up discovering it by doing a hexdump -c on the file and saw the first character was some sort of blank one.

0000000         r  \0   e  \0   s  \0   o  \0   u  \0   r  \0   c  \0
![image](https://user-images.githubusercontent.com/8010786/54504478-f026d480-4987-11e9-98e1-bb79caa8c7f8.png)

After using dos2unix to convert from UTF-16LE to UTF-8 Unix:

0000000   r   e   s   o   u   r   c   e       "   a   w   s   _   r   o

This allowed the TerraForm validate to successfully complete.

I'm not 100 sure it was your program at fault, but something I thought you and others should be aware of incase it happens to them.

Again thanks for the program, it's saved me so much time and work.

**Comment by carlpett** [comment]
Hey @Havoc302,
This is a Powershell peculiarity. It defaults to writing files with UTF-16 encoding, and the first two bytes there are the "byte order mark", or BOM. The overwhelming majority of tools use UTF-8, without a BOM, so then UTF-16 files get misinterpreted.
When writing files from Powershell, override the encoding like this:  `Out-File -Encoding utf8 ...`

**Comment by Havoc302** [comment]
Ah PS did it. Apologies. And thanks I'll fix up my script.
