### ISSUE TITLE
TXT record with more than 255 chars

### ISSUE THREAD

**Issue by ralgozino** [carlpett/tfz53#18]
Hi!

First of all let me thank you for creating this tool! It saved me tons of time and worked great! I've found this one issue though with one TXT record (DKIM) that had more than 255 chars. The record was splitted in two strings but the first string's closing quotes `"` and the second string's opening quotes `"` weren't scaped and included an space between them. According to the [AWS Terraform provider](https://www.terraform.io/docs/providers/aws/r/route53_record.html) the record should be splitted using `\"\"` (two scaped qoutes), luckily the error was captured by the VSCode plugin and by `terraform plan` and was easy to fix :)

It would be nice if the tool could do the replacement in automatic.

EDIT: I forgot to mention that I'm using the old syntax flag

Thanks again!

**Comment by carlpett** [comment]
Hi @ralgozino,
Thanks for the report! I'll try to add a test and fix for that soon!

**Comment by ralgozino** [comment]
Awesome! let me know if I can help. Thanks!

**Comment by carlpett** [comment]
@ralgozino I had some time to look into this now, and it would be helpful to see how the record looked in your source zone file. Such as what was quoted and not, etc. There are some rules around this already implemented in the DNS library, so I think there might be a conflict somewhere.

**Comment by ralgozino** [comment]
Hi @carlpett ! The record look like this:
```
google._domainkey	300	IN	TXT	"v=DKIM1; k=rsa; p=RABABIjANBgkqhkia9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6BmgzAvoUyUxmutxGBNXyhxGusY0EQdOACVqGQebN3yWpmbBzS/lSUo06vQco82gBj4banOytYdXAPylw0C3tYvJ7S5BtUH+FmC3TZBeIKOc5qt++dx6/aVawsE+WgKVigXDx925QOMtqcRhnAidK9k2Xy2X/TSbT7/vXc1tBI5OLpgBw0bJ6zFuwFYUTUim" "flD/4+EMyzMJtaeBNU4TyymgxAnwEJYi04AtHrAHAA153UsWprapSO9NRSUSVBT7Q+0DQYFiRgs7j7R65k4hOtEjPVatO2k4Ez7W+XvqXNq0Xkrdb/ebTWXgski/X7UIGnUKuC0aVBTvXFLBG1QbwIDAQAB"
```
In a zone file exported by a DNS provider

**Comment by carlpett** [comment]
Thanks! I have a PR open now, linked above which should handle this correctly. Could you give it a try and see if it outputs what you expect?

**Comment by ralgozino** [comment]
I've just re-converted the zone file using the PR branch and got the expected (right) resulting tf file, so I would say that the issue is fixed 👏 
Thanks!

**Comment by carlpett** [comment]
Thanks @ralgozino!
