### ISSUE TITLE
Please rename this tool

### ISSUE THREAD

**Issue by joshk0** [carlpett/tfz53#8]
I pretty much treat this program's name like a GUID, something I would never type out on my own but only copy and paste, and in the case of shell usage, i tab complete it from `bzf`.

It doesn't matter if the name doesn't really describe the product, just something that is easy to remember and manually type is fine.

How about `tfz53`? terraform + zone + 53?

**Comment by carlpett** [comment]
I agree :smile: Thanks for prodding me about it, it really should be changed. I like the `tfz53` proposal!
Currently I'm travelling, but I'll see if I can get this fixed over the weekend!
